repos:
  # TODO: Use Flake8
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: requirements-txt-fixer
        exclude: >-
          ^requirements/deterministic/.*.txt$
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-symlinks
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: detect-private-key
  - repo: local
    hooks:
      - id: check-compiled
        name: Check compiled requirements
        language: system
        entry: ./scripts/check-compiled.py
        files: >-
          ^requirements/.*.txt$
        exclude: >-
          ^requirements/deterministic/.*.txt$
        require_serial: true
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
