version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8089:8089"
    # For Development
    # volumes:
    #   - ./src:/code/src
    env_file:
      - .env

    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://localhost:8089/healthcheck"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
